default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "death_bloom") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>

development:
  <<: *default
  database: death_bloom_development

test:
  <<: *default
  database: death_bloom_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
